--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kj/photos/wallpapers/landscape-4.jpeg"

-- Special
background="#190621"
foreground="#c5c0c7"
cursor="#c5c0c7"

-- Colors
color0="#190621"
color1="#8123aa"
color2="#945aa7"
color3="#a6249d"
color4="#b14185"
color5="#ac1f6a"
color6="#aa1349"
color7="#c5c0c7"
color8="#524458"
color9="#8123aa"
color10="#945aa7"
color11="#a6249d"
color12="#b14185"
color13="#ac1f6a"
color14="#aa1349"
color15="#c5c0c7"
