# Shell variables
# Generated by 'wal'
wallpaper="/home/kj/photos/wallpapers/landscape-4.jpeg"

# Special
background='#190621'
foreground='#c5c0c7'
cursor='#c5c0c7'

# Colors
color0='#190621'
color1='#8123aa'
color2='#945aa7'
color3='#a6249d'
color4='#b14185'
color5='#ac1f6a'
color6='#aa1349'
color7='#c5c0c7'
color8='#524458'
color9='#8123aa'
color10='#945aa7'
color11='#a6249d'
color12='#b14185'
color13='#ac1f6a'
color14='#aa1349'
color15='#c5c0c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
