add_newline = true

[character]
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "bold bright-purple"

[git_branch]
format = "on [$symbol$branch]($style) "
style = "bold purple"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[package]
disabled = false
display_private = true
style = "bold blue"

[python]
format = "[$symbol$version]($style) "
style = "bold blue"

[nodejs]
style= "bold blue"

[username]
style_user = "bold dimmed blue"
show_always = false
