--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kj/photos/wallpapers/landscape-4.jpeg"

-- Special
background="#0f0312"
foreground="#f2aecb"
cursor="#f2aecb"

-- Colors
color0="#0f0312"
color1="#6A194A"
color2="#4D2546"
color3="#6F254D"
color4="#982357"
color5="#CD2864"
color6="#D32292"
color7="#f2aecb"
color8="#a9798e"
color9="#6A194A"
color10="#4D2546"
color11="#6F254D"
color12="#982357"
color13="#CD2864"
color14="#D32292"
color15="#f2aecb"
