# Shell variables
# Generated by 'wal'
wallpaper="/home/kj/photos/wallpapers/landscape-4.jpeg"

# Special
background='#0f0312'
foreground='#f2aecb'
cursor='#f2aecb'

# Colors
color0='#0f0312'
color1='#6A194A'
color2='#4D2546'
color3='#6F254D'
color4='#982357'
color5='#CD2864'
color6='#D32292'
color7='#f2aecb'
color8='#a9798e'
color9='#6A194A'
color10='#4D2546'
color11='#6F254D'
color12='#982357'
color13='#CD2864'
color14='#D32292'
color15='#f2aecb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
